namespace Ai.Tutor.Contracts.Enums;

/// <summary>
/// Represents the status of a conversation thread.
/// </summary>
public enum ThreadStatus
{
    /// <summary>
    /// The thread is currently active and can receive new messages.
    /// </summary>
    Active,

    /// <summary>
    /// The thread has been archived and is read-only.
    /// </summary>
    Archived,

    /// <summary>
    /// The thread has been marked as deleted.
    /// </summary>
    Deleted,
}

/// <summary>
/// Represents the delivery status of a message.
/// </summary>
public enum MessageStatus
{
    /// <summary>
    /// The message is currently being sent.
    /// </summary>
    Sending,

    /// <summary>
    /// The message has been successfully sent and delivered.
    /// </summary>
    Sent,

    /// <summary>
    /// An error occurred while sending the message.
    /// </summary>
    Error,
}

/// <summary>
/// Represents the type of sender for a message.
/// </summary>
public enum SenderType
{
    /// <summary>
    /// The message was sent by a human user.
    /// </summary>
    User,

    /// <summary>
    /// The message was generated by an AI assistant.
    /// </summary>
    Ai,
}

/// <summary>
/// Represents the type of a folder in the system.
/// </summary>
public enum FolderType
{
    /// <summary>
    /// A project folder that can contain other folders and threads.
    /// </summary>
    Project,

    /// <summary>
    /// A regular folder that can contain threads.
    /// </summary>
    Folder,
}

/// <summary>
/// Represents the status of a folder.
/// </summary>
public enum FolderStatus
{
    /// <summary>
    /// The folder is active and visible.
    /// </summary>
    Active,

    /// <summary>
    /// The folder has been archived and is read-only.
    /// </summary>
    Archived,

    /// <summary>
    /// The folder has been marked as deleted.
    /// </summary>
    Deleted,
}

/// <summary>
/// Represents the type of an attachment.
/// </summary>
public enum AttachmentType
{
    /// <summary>
    /// A document file (e.g., PDF, DOCX).
    /// </summary>
    Document,

    /// <summary>
    /// An image file (e.g., JPG, PNG).
    /// </summary>
    Image,

    /// <summary>
    /// Any other type of file.
    /// </summary>
    Other,
}

/// <summary>
/// Represents the type of a reference in the system.
/// </summary>
public enum ReferenceType
{
    /// <summary>
    /// A reference to a file.
    /// </summary>
    File,

    /// <summary>
    /// A reference to a specific page.
    /// </summary>
    Page,

    /// <summary>
    /// A reference to a video.
    /// </summary>
    Video,

    /// <summary>
    /// A reference to a web link.
    /// </summary>
    Link,

    /// <summary>
    /// A reference to a mathematical formula.
    /// </summary>
    Formula,
}

public enum EventType
{
    MessageCreated,
    MessageUpdated,
    MessageDeleted,
}

public enum OrgType
{
    Personal,
    Education,
    Household,
    Business,
}

public enum OrgRole
{
    Owner,
    Admin,
    Member,
}
